### ISSUE TITLE
Status: Failed to start: ENOENT: no such file or directory 'index.html'

### ISSUE THREAD

**Issue by hailigsblechle** [VladimirKalachikhin/e-inkDashboard#2]
Upon initial it shows the following error in plugin config:

`
Status: Failed to start: ENOENT: no such file or directory, open '/home/pi/.signalk/node_modules/e-inkdashboard/public/index.html'
`

**Comment by VladimirKalachikhin** [comment]
Perhaps something has changed in the SignalK...

Update e-inkdashboard. Is it works now?

**Comment by VladimirKalachikhin** [comment]
Fixed.
